### ISSUE TITLE
Testcases not passing

### ISSUE THREAD

**Issue by sandy4245** [aakashmt97/Quora#10]
Unit Test cases were not passing despite all scenarios working fine when application is run on Swagger UI.

**Comment by aakashmt97** [comment]
Searched for possible solution for the failure of Unit Tests cases but it did not work.

**Comment by aakashmt97** [comment]
After searching more we realized the problem was lying in RestExceptionHandler class.

**Comment by aakashmt97** [comment]
The problem was that the HttpStatus code in RestExceptionHandler class was assigned as Unauthorized.

**Comment by aakashmt97** [comment]
So we changed HttpStatus of InvalidQuestionException, UserNotFoundException, AnswerNotFoundException to NOT_FOUND and HttpStatus code of AuthorizationFailedException  to FORBIIDDEN

**Comment by aakashmt97** [comment]
After updating the RestExceptionHandler, we run the Unit Test cases and it worked. All the Test Cases passed without throwing any error.
